/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_vista;

import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Usuari
 */
public class ReproduccionsPanel extends javax.swing.JPanel {
    
    public ReproduccionsPanel() {
        initComponents();
        initManualComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        IDClientFiltres_Label = new javax.swing.JLabel();
        IDClientFiltres_CB = new javax.swing.JComboBox<>();
        IDCatalegFiltres_Label = new javax.swing.JLabel();
        IDCatalegFiltres_CB = new javax.swing.JComboBox<>();
        DataFiltres_Label = new javax.swing.JLabel();
        Data_JCalendar1 = new com.toedter.calendar.JDateChooser();
        Data_JCalendar2 = new com.toedter.calendar.JDateChooser();
        IDClient_Label = new javax.swing.JLabel();
        IDClient_CB = new javax.swing.JComboBox<>();
        Data_Label = new javax.swing.JLabel();
        IDCataleg_Label = new javax.swing.JLabel();
        IDCataleg_CB = new javax.swing.JComboBox<>();
        Crear_Button = new javax.swing.JButton();
        Actualitzar_Button = new javax.swing.JButton();
        Borrar_Button = new javax.swing.JButton();
        Pestaña_Label = new javax.swing.JLabel();
        BuscarFiltres_Button = new javax.swing.JButton();
        ImprimirFiltres_Button = new javax.swing.JButton();
        Data_JCalendar = new com.toedter.calendar.JDateChooser();

        jToolBar1.setRollover(true);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Client", "Data", "ID Catàleg", "Títol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowHorizontalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FILTRES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12))); // NOI18N

        IDClientFiltres_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        IDClientFiltres_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDClientFiltres_Label.setText("ID Client");

        IDClientFiltres_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        IDClientFiltres_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDClientFiltres_CBActionPerformed(evt);
            }
        });

        IDCatalegFiltres_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        IDCatalegFiltres_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDCatalegFiltres_Label.setText("ID Catàleg");

        IDCatalegFiltres_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        IDCatalegFiltres_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDCatalegFiltres_CBActionPerformed(evt);
            }
        });

        DataFiltres_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        DataFiltres_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataFiltres_Label.setText("Datas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IDClientFiltres_Label))
                    .addComponent(IDClientFiltres_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDCatalegFiltres_Label)
                        .addGap(51, 51, 51)
                        .addComponent(DataFiltres_Label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDCatalegFiltres_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Data_JCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Data_JCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDClientFiltres_Label)
                        .addComponent(IDCatalegFiltres_Label))
                    .addComponent(DataFiltres_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDCatalegFiltres_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDClientFiltres_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Data_JCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(Data_JCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        IDClient_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        IDClient_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDClient_Label.setText("ID Client");

        IDClient_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        IDClient_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDClient_CBActionPerformed(evt);
            }
        });

        Data_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Data_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Data_Label.setText("Data");

        IDCataleg_Label.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        IDCataleg_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDCataleg_Label.setText("ID Catàleg");

        IDCataleg_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        IDCataleg_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDCataleg_CBActionPerformed(evt);
            }
        });

        Crear_Button.setText("Crear");

        Actualitzar_Button.setText("Actualitzar");

        Borrar_Button.setText("Borrar");

        Pestaña_Label.setFont(new java.awt.Font("Consolas", 3, 12)); // NOI18N
        Pestaña_Label.setText("REPRODUCCIONS");

        BuscarFiltres_Button.setText("Buscar");

        ImprimirFiltres_Button.setText("Imprimir");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarFiltres_Button)
                            .addComponent(ImprimirFiltres_Button))
                        .addGap(29, 29, 29)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Actualitzar_Button)
                                .addGap(78, 78, 78))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Crear_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Borrar_Button)
                                .addGap(18, 18, 18))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IDCataleg_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(IDClient_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Data_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(IDCataleg_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(IDClient_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                                .addGap(0, 141, Short.MAX_VALUE)
                                                .addComponent(Pestaña_Label)))))
                                .addContainerGap())
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(Data_JCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(Pestaña_Label)
                        .addGap(40, 40, 40)
                        .addComponent(IDClient_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDClient_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Data_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Data_JCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(IDCataleg_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDCataleg_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(Actualitzar_Button))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Borrar_Button)
                                    .addComponent(Crear_Button)
                                    .addComponent(BuscarFiltres_Button))
                                .addGap(18, 18, 18)
                                .addComponent(ImprimirFiltres_Button)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void IDClient_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDClient_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDClient_CBActionPerformed

    private void IDCataleg_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDCataleg_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDCataleg_CBActionPerformed

    private void IDClientFiltres_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDClientFiltres_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDClientFiltres_CBActionPerformed

    private void IDCatalegFiltres_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDCatalegFiltres_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDCatalegFiltres_CBActionPerformed
    
    public void initManualComponents(){

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualitzar_Button;
    private javax.swing.JButton Borrar_Button;
    private javax.swing.JButton BuscarFiltres_Button;
    private javax.swing.JButton Crear_Button;
    private javax.swing.JLabel DataFiltres_Label;
    private com.toedter.calendar.JDateChooser Data_JCalendar;
    private com.toedter.calendar.JDateChooser Data_JCalendar1;
    private com.toedter.calendar.JDateChooser Data_JCalendar2;
    private javax.swing.JLabel Data_Label;
    private javax.swing.JComboBox<String> IDCatalegFiltres_CB;
    private javax.swing.JLabel IDCatalegFiltres_Label;
    private javax.swing.JComboBox<String> IDCataleg_CB;
    private javax.swing.JLabel IDCataleg_Label;
    private javax.swing.JComboBox<String> IDClientFiltres_CB;
    private javax.swing.JLabel IDClientFiltres_Label;
    private javax.swing.JComboBox<String> IDClient_CB;
    private javax.swing.JLabel IDClient_Label;
    private javax.swing.JButton ImprimirFiltres_Button;
    private javax.swing.JLabel Pestaña_Label;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
