--AFEGIR PAISOS
insert into pais values('AF','Afganistán');
insert into pais values('AL','Albania');
insert into pais values('DE','Alemania');
insert into pais values('DZ','Algeria');
insert into pais values('AD','Andorra');
insert into pais values('AO','Angola');
insert into pais values('AI','Anguila');
insert into pais values('AQ','Antártida');
insert into pais values('AG','Antigua y Barbuda');
insert into pais values('AN','Antillas Neerlandesas');
insert into pais values('SA','Arabia Saudita');
insert into pais values('AR','Argentina');
insert into pais values('AM','Armenia');
insert into pais values('AW','Aruba');
insert into pais values('AU','Australia');
insert into pais values('AT','Austria');
insert into pais values('AZ','Azerbayán');
insert into pais values('BE','Bélgica');
insert into pais values('BS','Bahamas');
insert into pais values('BH','Bahrein');
insert into pais values('BD','Bangladesh');
insert into pais values('BB','Barbados');
insert into pais values('BZ','Belice');
insert into pais values('BJ','Benín');
insert into pais values('BT','Bhután');
insert into pais values('BY','Bielorrusia');
insert into pais values('MM','Birmania');
insert into pais values('BO','Bolivia');
insert into pais values('BA','Bosnia y Herzegovina');
insert into pais values('BW','Botsuana');
insert into pais values('BR','Brasil');
insert into pais values('BN','Brunéi');
insert into pais values('BG','Bulgaria');
insert into pais values('BF','Burkina Faso');
insert into pais values('BI','Burundi');
insert into pais values('CV','Cabo Verde');
insert into pais values('KH','Camboya');
insert into pais values('CM','Camerún');
insert into pais values('CA','Canadá');
insert into pais values('TD','Chad');
insert into pais values('CL','Chile');
insert into pais values('CN','China');
insert into pais values('CY','Chipre');
insert into pais values('VA','Ciudad del Vaticano');
insert into pais values('CO','Colombia');
insert into pais values('KM','Comoras');
insert into pais values('CG','Congo');
insert into pais values('CD','República Democrática del Congo');
insert into pais values('KP','Corea del Norte');
insert into pais values('KR','Corea del Sur');
insert into pais values('CI','Costa de Marfil');
insert into pais values('CR','Costa Rica');
insert into pais values('HR','Croacia');
insert into pais values('CU','Cuba');
insert into pais values('DK','Dinamarca');
insert into pais values('DM','Dominica');
insert into pais values('EC','Ecuador');
insert into pais values('EG','Egipto');
insert into pais values('SV','El Salvador');
insert into pais values('AE','Emiratos Árabes Unidos');
insert into pais values('ER','Eritrea');
insert into pais values('SK','Eslovaquia');
insert into pais values('SI','Eslovenia');
insert into pais values('ES','España');
insert into pais values('US','Estados Unidos de América');
insert into pais values('EE','Estonia');
insert into pais values('ET','Etiopía');
insert into pais values('PH','Filipinas');
insert into pais values('FI','Finlandia');
insert into pais values('FJ','Fiyi');
insert into pais values('FR','Francia');
insert into pais values('GA','Gabón');
insert into pais values('GM','Gambia');
insert into pais values('GE','Georgia');
insert into pais values('GH','Ghana');
insert into pais values('GI','Gibraltar');
insert into pais values('GD','Granada');
insert into pais values('GR','Grecia');
insert into pais values('GL','Groenlandia');
insert into pais values('GP','Guadalupe');
insert into pais values('GU','Guam');
insert into pais values('GT','Guatemala');
insert into pais values('GF','Guayana Francesa');
insert into pais values('GG','Guernsey');
insert into pais values('GN','Guinea');
insert into pais values('GQ','Guinea Ecuatorial');
insert into pais values('GW','Guinea-Bissau');
insert into pais values('GY','Guyana');
insert into pais values('HT','Haití');
insert into pais values('HN','Honduras');
insert into pais values('HK','Hong kong');
insert into pais values('HU','Hungría');
insert into pais values('IN','India');
insert into pais values('ID','Indonesia');
insert into pais values('IR','Irán');
insert into pais values('IQ','Irak');
insert into pais values('IE','Irlanda');
insert into pais values('BV','Isla Bouvet');
insert into pais values('IM','Isla de Man');
insert into pais values('CX','Isla de Navidad');
insert into pais values('NF','Isla Norfolk');
insert into pais values('IS','Islandia');
insert into pais values('BM','Islas Bermudas');
insert into pais values('KY','Islas Caimán');
insert into pais values('CC','Islas Cocos (Keeling)');
insert into pais values('CK','Islas Cook');
insert into pais values('AX','Islas de Åland');
insert into pais values('FO','Islas Feroe');
insert into pais values('GS','Islas Georgias del Sur y Sandwich del Sur');
insert into pais values('HM','Islas Heard y McDonald');
insert into pais values('MV','Islas Maldivas');
insert into pais values('FK','Islas Malvinas');
insert into pais values('MP','Islas Marianas del Norte');
insert into pais values('MH','Islas Marshall');
insert into pais values('PN','Islas Pitcairn');
insert into pais values('SB','Islas Salomón');
insert into pais values('TC','Islas Turcas y Caicos');
insert into pais values('UM','Islas Ultramarinas Menores de Estados Unidos');
insert into pais values('VG','Islas Vírgenes Británicas');
insert into pais values('VI','Islas Vírgenes de los Estados Unidos');
insert into pais values('IL','Israel');
insert into pais values('IT','Italia');
insert into pais values('JM','Jamaica');
insert into pais values('JP','Japón');
insert into pais values('JE','Jersey');
insert into pais values('JO','Jordania');
insert into pais values('KZ','Kazajistán');
insert into pais values('KE','Kenia');
insert into pais values('KG','Kirgizstán');
insert into pais values('KI','Kiribati');
insert into pais values('KW','Kuwait');
insert into pais values('LB','Líbano');
insert into pais values('LA','Laos');
insert into pais values('LS','Lesoto');
insert into pais values('LV','Letonia');
insert into pais values('LR','Liberia');
insert into pais values('LY','Libia');
insert into pais values('LI','Liechtenstein');
insert into pais values('LT','Lituania');
insert into pais values('LU','Luxemburgo');
insert into pais values('MX','México');
insert into pais values('MC','Mónaco');
insert into pais values('MO','Macao');
insert into pais values('MK','Macedônia');
insert into pais values('MG','Madagascar');
insert into pais values('MY','Malasia');
insert into pais values('MW','Malawi');
insert into pais values('ML','Mali');
insert into pais values('MT','Malta');
insert into pais values('MA','Marruecos');
insert into pais values('MQ','Martinica');
insert into pais values('MU','Mauricio');
insert into pais values('MR','Mauritania');
insert into pais values('YT','Mayotte');
insert into pais values('FM','Micronesia');
insert into pais values('MD','Moldavia');
insert into pais values('MN','Mongolia');
insert into pais values('ME','Montenegro');
insert into pais values('MS','Montserrat');
insert into pais values('MZ','Mozambique');
insert into pais values('NA','Namibia');
insert into pais values('NR','Nauru');
insert into pais values('NP','Nepal');
insert into pais values('NI','Nicaragua');
insert into pais values('NE','Niger');
insert into pais values('NG','Nigeria');
insert into pais values('NU','Niue');
insert into pais values('NO','Noruega');
insert into pais values('NC','Nueva Caledonia');
insert into pais values('NZ','Nueva Zelanda');
insert into pais values('OM','Omán');
insert into pais values('NL','Países Bajos');
insert into pais values('PK','Pakistán');
insert into pais values('PW','Palau');
insert into pais values('PS','Palestina');
insert into pais values('PA','Panamá');
insert into pais values('PG','Papúa Nueva Guinea');
insert into pais values('PY','Paraguay');
insert into pais values('PE','Perú');
insert into pais values('PF','Polinesia Francesa');
insert into pais values('PL','Polonia');
insert into pais values('PT','Portugal');
insert into pais values('PR','Puerto Rico');
insert into pais values('QA','Qatar');
insert into pais values('GB','Reino Unido');
insert into pais values('CF','República Centroafricana');
insert into pais values('CZ','República Checa');
insert into pais values('DO','República Dominicana');
insert into pais values('RE','Reunión');
insert into pais values('RW','Ruanda');
insert into pais values('RO','Rumanía');
insert into pais values('RU','Rusia');
insert into pais values('EH','Sahara Occidental');
insert into pais values('WS','Samoa');
insert into pais values('AS','Samoa Americana');
insert into pais values('BL','San Bartolomé');
insert into pais values('KN','San Cristóbal y Nieves');
insert into pais values('SM','San Marino');
insert into pais values('MF','San Martín (Francia)');
insert into pais values('PM','San Pedro y Miquelón');
insert into pais values('VC','San Vicente y las Granadinas');
insert into pais values('SH','Santa Elena');
insert into pais values('LC','Santa Lucía');
insert into pais values('ST','Santo Tomé y Príncipe');
insert into pais values('SN','Senegal');
insert into pais values('RS','Serbia');
insert into pais values('SC','Seychelles');
insert into pais values('SL','Sierra Leona');
insert into pais values('SG','Singapur');
insert into pais values('SY','Siria');
insert into pais values('SO','Somalia');
insert into pais values('LK','Sri lanka');
insert into pais values('ZA','Sudáfrica');
insert into pais values('SD','Sudán');
insert into pais values('SE','Suecia');
insert into pais values('CH','Suiza');
insert into pais values('SR','Surinám');
insert into pais values('SJ','Svalbard y Jan Mayen');
insert into pais values('SZ','Swazilandia');
insert into pais values('TJ','Tadjikistán');
insert into pais values('TH','Tailandia');
insert into pais values('TW','Taiwán');
insert into pais values('TZ','Tanzania');
insert into pais values('IO','Territorio Británico del Océano Índico');
insert into pais values('TF','Territorios Australes y Antárticas Franceses');
insert into pais values('TL','Timor Oriental');
insert into pais values('TG','Togo');
insert into pais values('TK','Tokelau');
insert into pais values('TO','Tonga');
insert into pais values('TT','Trinidad y Tobago');
insert into pais values('TN','Tunez');
insert into pais values('TM','Turkmenistán');
insert into pais values('TR','Turquía');
insert into pais values('TV','Tuvalu');
insert into pais values('UA','Ucrania');
insert into pais values('UG','Uganda');
insert into pais values('UY','Uruguay');
insert into pais values('UZ','Uzbekistán');
insert into pais values('VU','Vanuatu');
insert into pais values('VE','Venezuela');
insert into pais values('VN','Vietnam');
insert into pais values('WF','Wallis y Futuna');
insert into pais values('YE','Yemen');
insert into pais values('DJ','Yibuti');
insert into pais values('ZM','Zambia');
insert into pais values('ZW','Zimbabue');

--AFEGIR ESTILS
insert into estil values(0,'Cancion melodica');
insert into estil values(NULL,'Cantopop');
insert into estil values(NULL,'Cristiana');
insert into estil values(NULL,'Death Metal');
insert into estil values(NULL,'Electrónica');
insert into estil values(NULL,'Electro House');
insert into estil values(NULL,'Folk');
insert into estil values(NULL,'Fusión');
insert into estil values(NULL,'Future Fank');
insert into estil values(NULL,'Glam Rock');
insert into estil values(NULL,'Grunge');
insert into estil values(NULL,'Hip Hop');
insert into estil values(NULL,'House');
insert into estil values(NULL,'Italo Dance');
insert into estil values(NULL,'Jota');
insert into estil values(NULL,'Militar');
insert into estil values(NULL,'Metal');
insert into estil values(NULL,'New Age');
insert into estil values(NULL,'New Wave');
insert into estil values(NULL,'Nightcore');
insert into estil values(NULL,'Occidental');
insert into estil values(NULL,'Orquesta');
insert into estil values(NULL,'Pachanga');
insert into estil values(NULL,'Pop');
insert into estil values(NULL,'Pop-Rock');
insert into estil values(NULL,'Psychobilly');
insert into estil values(NULL,'Rap');
insert into estil values(NULL,'Rap Metal');
insert into estil values(NULL,'Reggae');
insert into estil values(NULL,'Reggaeton');
insert into estil values(NULL,'Rock');
insert into estil values(NULL,'Rock progresivo');
insert into estil values(NULL,'Seapunk');
insert into estil values(NULL,'Shred');
insert into estil values(NULL,'Ska');
insert into estil values(NULL,'Slow Dance');
insert into estil values(NULL,'Synth-Rock');
insert into estil values(NULL,'Synth-Wave');
insert into estil values(NULL,'Trap');
insert into estil values(NULL,'Trap Metal');
insert into estil values(NULL,'Trovador');
insert into estil values(NULL,'Vaporwave');

--AFEGIR ARTISTA
insert into artista values (0,'Pearl Jam','G');
insert into artista values (NULL,'Foo Fighters','G');
insert into artista values (NULL,'Nirvana','G');
insert into artista values (NULL,'Tears For Fears','G');
insert into artista values (NULL,'Pantera','G');
insert into artista values (NULL,'Ozzy Osbourne','I');
insert into artista values (NULL,'Boston','G');
insert into artista values (NULL,'Toto','G');
insert into artista values (NULL,'Metallica','G');
insert into artista values (NULL,'Rage Against The Machine','G');
insert into artista values (NULL,'Lynyrd Skynyrd','G');
insert into artista values (NULL,'Megadeth','G');
insert into artista values (NULL,'ZZ Top','G');
insert into artista values (NULL,'Black Sabbath','G');
insert into artista values (NULL,'Led Zeppelin','G');
insert into artista values (NULL,'Jimi Hendrix','I');
insert into artista values (NULL,'Guns N Roses','G');
insert into artista values (NULL,'Pink Floyd','G');
insert into artista values (NULL,'Slipknot','G');
insert into artista values (NULL,'The Cranberries','G');
insert into artista values (NULL,'Amy Winehouse','I');
insert into artista values (NULL,'Michael Jackson','I');
insert into artista values (NULL,'B. B. King','I');
insert into artista values (NULL,'Steve Vai','I');
insert into artista values (NULL,'Santana','I');
insert into artista values (NULL,'Stevie Ray Vaughan','I');
insert into artista values (NULL,'Slash','I');
insert into artista values (NULL,'Oasis','G');
insert into artista values (NULL,'Eminem','I');
insert into artista values (NULL,'Notorious B.I.G.','I');
insert into artista values (NULL,'Ice Cube','I');
insert into artista values (NULL,'2Pac','I');
insert into artista values (NULL,'50 Cent','I');
insert into artista values (NULL,'Dr. Dre','I');
insert into artista values (NULL,'Coolio','I');

--AFEGIR ART_IND
insert into art_ind values (5, '03/12/1948', 'GB');
insert into art_ind values (15, '27/11/1942', 'US');
insert into art_ind values (20, '14/09/1983', 'GB');
insert into art_ind values (21, '29/08/1958', 'US');
insert into art_ind values (22, '16/09/1925', 'US');
insert into art_ind values (23, '06/06/1960', 'US');

--AFEGIR ART_GRUP
insert into art_grup values (0, '01/01/1990');
insert into art_grup values (1, '01/01/1994');

--AFEGIR CATALEG
insert into cataleg values (0,'Once','S',10,'C');
insert into cataleg values (NULL,'Alive','S',10,'C');
insert into cataleg values (NULL,'Black','S',10,'C');
insert into cataleg values (NULL,'Even Flow','S',10,'C');
insert into cataleg values (NULL,'Why Go','S',10,'C');
insert into cataleg values (NULL,'Jeremy','S',10,'C');

insert into cataleg values (NULL,'Dive','S',10,'C');
insert into cataleg values (NULL,'Turnaround','S',10,'C');
insert into cataleg values (NULL,'Sliver','S',10,'C');
insert into cataleg values (NULL,'Been a Son','S',10,'C');
insert into cataleg values (NULL,'Aneurysm','S',10,'C');
insert into cataleg values (NULL,'(New Wave) Polly','S',10,'C');

insert into cataleg values (NULL,'Ten','S',10,'A');
insert into cataleg values (NULL,'Incesticide','S',10,'A');

insert into cataleg values (NULL,'Exitos del Grunge','S',10,'L');
insert into cataleg values (NULL,'Exitos del Metal','S',16,'L');

--AFEGIR CANSO
insert into canso values (0, '01/01/1991', 232, 0);
insert into canso values (1, '01/01/1991', 341, 0);
insert into canso values (2, '01/01/1991', 339, 0);
insert into canso values (3, '01/01/1991', 294, 0);
insert into canso values (4, '01/01/1991', 199, 0);
insert into canso values (5, '01/01/1991', 319, 0);

insert into canso values (6, '14/12/1992', 355, 2);
insert into canso values (7, '14/12/1992', 139, 2);
insert into canso values (8, '14/12/1992', 134, 2);
insert into canso values (9, '14/12/1992', 116, 2);
insert into canso values (10, '14/12/1992', 275, 2);
insert into canso values (11, '14/12/1992', 108, 2);

--AFEGIR ALBUM
insert into album values (12, 3206, '01/01/1991');
insert into album values (13, 2684, '01/01/1992');

--AFEGIR ALBUM_CONTINGUT
insert into album_contingut values (12, 0, 1);
insert into album_contingut values (12, 1, 3);
insert into album_contingut values (12, 2, 5);
insert into album_contingut values (12, 3, 2);
insert into album_contingut values (12, 4, 4);
insert into album_contingut values (12, 5, 6);

insert into album_contingut values (13, 6, 1);
insert into album_contingut values (13, 7, 5);
insert into album_contingut values (13, 8, 2);
insert into album_contingut values (13, 9, 4);
insert into album_contingut values (13, 10, 15);
insert into album_contingut values (13, 11, 8);

--AFEGIR LLISTA
insert into llista values (14, 3581);
insert into llista values (15, 3257);

--AFEGIR LLISTA_CONTINGUT
insert into llista_contingut values (14, 12, 1);
insert into llista_contingut values (14, 6, 2);
insert into llista_contingut values (14, 7, 3);

insert into llista_contingut values (15, 13, 1);
insert into llista_contingut values (15, 0, 2);
insert into llista_contingut values (15, 1, 3);

--AFEGIR CLIENT
insert into client values (0, 'virtualclient@hotmail.com', 'Virtual', 'Client', '01/01/2000', 08788, 'Carrer de la Virtualitzacio', NULL,	 'Digitalandia', 'ES');
insert into client values (NULL, 'client1@hotmail.com', 'Primer', 'Client', '01/01/2004', 08788, 'Carrer del Primer Client', NULL, 'Humalandia', 'ES');
insert into client values (NULL, 'client2@hotmail.com', 'Segon', 'Client', '01/01/2002', 08788, 'Carrer del Segon Client', NULL, 'Humalandia', 'ES');

--AFEGIR REPRODUCCIO
insert into reproduccio values (0, '01/02/2000', 0);
--insert into reproduccio values (0, '01/02/2000', 12);
--insert into reproduccio values (0, '01/02/2000', 14);

insert into reproduccio values (1, '01/02/2004', 1);
--insert into reproduccio values (1, '01/02/2004', 12);
--insert into reproduccio values (1, '01/02/2004', 14);

insert into reproduccio values (2, '01/02/2002', 2);
--insert into reproduccio values (2, '01/02/2002', 12);
--insert into reproduccio values (2, '01/02/2002', 14);